// === TACTICAL SCENARIOS ===
// Each scenario defines a match situation with player positions,
// movement arrows, and a Spanish question
//
// Coordinate system (team attacks left-to-right):
//   x: 0 = own goal line, 100 = opponent goal line
//   y: 0 = top of screen = LEFT side (vänster) from player perspective
//   y: 100 = bottom of screen = RIGHT side (höger) from player perspective

const TACTICAL_SCENARIOS = [
    {
        id: 'profundidad',
        title: 'Djupledspassning',
        situation: 'Mittfältaren (10) har bollen i uppspelsläge. Anfallaren (9) gör en löpning bakom försvarslinjen.',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 20, y: 80, num: 2 },
            { x: 18, y: 60, num: 4 },
            { x: 18, y: 40, num: 5 },
            { x: 20, y: 20, num: 3 },
            { x: 35, y: 75, num: 6 },
            { x: 38, y: 50, num: 8 },
            { x: 35, y: 25, num: 7 },
            { x: 50, y: 70, num: 10, hasBall: true },
            { x: 50, y: 30, num: 11 },
            { x: 58, y: 50, num: 9 },
        ],
        awayPlayers: [
            { x: 95, y: 50, num: 1, role: 'gk' },
            { x: 75, y: 75, num: 2 },
            { x: 70, y: 58, num: 4 },
            { x: 70, y: 42, num: 5 },
            { x: 75, y: 25, num: 3 },
            { x: 60, y: 60, num: 6 },
            { x: 60, y: 40, num: 8 },
        ],
        arrows: [
            { fromX: 50, fromY: 70, toX: 72, toY: 58, type: 'pass', label: '?' },
            { fromX: 58, fromY: 50, toX: 73, toY: 55, type: 'run' },
        ],
        question: 'Vad ropar tränaren till 10?',
        options: [
            '¡Mete un pase en profundidad!',
            '¡Centra al área!',
            '¡Juega de primera!',
            '¡Despeja el balón!',
        ],
        correctIndex: 0,
        explanation: '"Pase en profundidad" = djupledspassning. Bollen spelas i luckan bakom försvarslinjen.',
    },
    {
        id: 'presion',
        title: 'Hög press',
        situation: 'Motståndarens målvakt har bollen. Tränaren vill att laget pressar högt.',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 30, y: 80, num: 2 },
            { x: 28, y: 60, num: 4 },
            { x: 28, y: 40, num: 5 },
            { x: 30, y: 20, num: 3 },
            { x: 55, y: 70, num: 6 },
            { x: 55, y: 50, num: 8 },
            { x: 55, y: 30, num: 7 },
            { x: 72, y: 60, num: 10 },
            { x: 70, y: 40, num: 11 },
            { x: 75, y: 50, num: 9, highlight: true },
        ],
        awayPlayers: [
            { x: 92, y: 50, num: 1, role: 'gk', hasBall: true },
            { x: 82, y: 70, num: 4 },
            { x: 82, y: 30, num: 5 },
        ],
        arrows: [
            { fromX: 75, fromY: 50, toX: 88, toY: 50, type: 'press' },
            { fromX: 72, fromY: 60, toX: 82, toY: 66, type: 'press' },
            { fromX: 70, fromY: 40, toX: 82, toY: 34, type: 'press' },
        ],
        question: 'Vad skriker tränaren från sidlinjen?',
        options: [
            '¡Presiona arriba!',
            '¡Repliega!',
            '¡Aguanta el balón!',
            '¡Tranquilo!',
        ],
        correctIndex: 0,
        explanation: '"Presionar arriba" = pressa högt. Laget trycker upp och ger motståndaren ingen tid.',
    },
    {
        id: 'centro',
        title: 'Inlägg',
        situation: 'Yttern (11) har tagit sig till ändlinjen på högerkanten. Anfallaren (9) och mittfältaren (8) är i straffområdet.',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 25, y: 80, num: 2 },
            { x: 22, y: 60, num: 4 },
            { x: 22, y: 40, num: 5 },
            { x: 25, y: 20, num: 3 },
            { x: 45, y: 50, num: 6 },
            { x: 75, y: 45, num: 8 },
            { x: 50, y: 20, num: 7 },
            { x: 65, y: 60, num: 10 },
            { x: 88, y: 85, num: 11, hasBall: true },
            { x: 80, y: 55, num: 9 },
        ],
        awayPlayers: [
            { x: 95, y: 50, num: 1, role: 'gk' },
            { x: 80, y: 70, num: 2 },
            { x: 78, y: 45, num: 5 },
            { x: 82, y: 35, num: 4 },
        ],
        arrows: [
            { fromX: 88, fromY: 85, toX: 82, toY: 52, type: 'pass', label: '?' },
            { fromX: 80, fromY: 55, toX: 85, toY: 58, type: 'run' },
            { fromX: 75, fromY: 45, toX: 82, toY: 48, type: 'run' },
        ],
        question: 'Vad ropar anfallaren (9) till yttern (11)?',
        options: [
            '¡Centra al segundo palo!',
            '¡Échala fuera!',
            '¡Pásala atrás!',
            '¡Baja a defender!',
        ],
        correctIndex: 0,
        explanation: '"Centrar al segundo palo" = slå in mot bortre stolpen. En klassisk situation i fotboll.',
    },
    {
        id: 'contraataque',
        title: 'Kontring',
        situation: 'Laget vinner tillbaka bollen i eget halvplan. Det är 3 mot 2 i en snabb kontring!',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 22, y: 75, num: 2 },
            { x: 20, y: 55, num: 4 },
            { x: 20, y: 45, num: 5 },
            { x: 22, y: 25, num: 3 },
            { x: 38, y: 50, num: 8, hasBall: true },
            { x: 35, y: 70, num: 6 },
            { x: 35, y: 30, num: 7 },
            { x: 48, y: 65, num: 10 },
            { x: 50, y: 30, num: 11 },
            { x: 52, y: 50, num: 9 },
        ],
        awayPlayers: [
            { x: 95, y: 50, num: 1, role: 'gk' },
            { x: 70, y: 60, num: 4 },
            { x: 70, y: 40, num: 5 },
        ],
        arrows: [
            { fromX: 38, fromY: 50, toX: 65, toY: 50, type: 'pass' },
            { fromX: 52, fromY: 50, toX: 78, toY: 52, type: 'run' },
            { fromX: 48, fromY: 65, toX: 72, toY: 68, type: 'run' },
            { fromX: 50, fromY: 30, toX: 72, toY: 35, type: 'run' },
        ],
        question: 'Vad skriker mittfältaren (8) när han vinner bollen?',
        options: [
            '¡Contraataque rápido!',
            '¡Replieguen todos!',
            '¡Tiempo, tranquilo!',
            '¡Cierra el espacio!',
        ],
        correctIndex: 0,
        explanation: '"Contraataque rápido" = snabb kontring. Alla springer framåt för att utnyttja övertalet.',
    },
    {
        id: 'pared',
        title: 'Väggpassning',
        situation: 'Mittfältaren (10) vill ta sig förbi motståndaren med en väggpassning med anfallaren (9).',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 22, y: 75, num: 2 },
            { x: 20, y: 60, num: 4 },
            { x: 20, y: 40, num: 5 },
            { x: 22, y: 25, num: 3 },
            { x: 40, y: 60, num: 6 },
            { x: 40, y: 40, num: 8 },
            { x: 48, y: 20, num: 7 },
            { x: 55, y: 55, num: 10, hasBall: true },
            { x: 48, y: 80, num: 11 },
            { x: 65, y: 60, num: 9 },
        ],
        awayPlayers: [
            { x: 95, y: 50, num: 1, role: 'gk' },
            { x: 75, y: 70, num: 2 },
            { x: 72, y: 55, num: 4 },
            { x: 72, y: 45, num: 5 },
            { x: 60, y: 52, num: 6 },
        ],
        arrows: [
            { fromX: 55, fromY: 55, toX: 65, toY: 60, type: 'pass' },
            { fromX: 65, fromY: 60, toX: 68, toY: 62, type: 'pass', label: '1-2' },
            { fromX: 55, fromY: 55, toX: 68, toY: 65, type: 'run' },
        ],
        question: 'Vad ropar 10 till 9?',
        options: [
            '¡Haz una pared conmigo!',
            '¡Tira a portería!',
            '¡Déjala, que viene!',
            '¡Sube la banda!',
        ],
        correctIndex: 0,
        explanation: '"Pared" = väggpassning (1-2). Spelaren passar, springer förbi, och får tillbaka bollen.',
    },
    {
        id: 'linea',
        title: 'Offsidefällan',
        situation: 'Motståndarens mittfältare försöker spela en djupledsboll. Mittbacken (4) styr offsidefällan.',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 35, y: 80, num: 2 },
            { x: 35, y: 60, num: 4, highlight: true },
            { x: 35, y: 40, num: 5 },
            { x: 35, y: 20, num: 3 },
            { x: 50, y: 65, num: 6 },
            { x: 50, y: 50, num: 8 },
            { x: 50, y: 35, num: 7 },
            { x: 65, y: 70, num: 10 },
            { x: 65, y: 30, num: 11 },
            { x: 70, y: 50, num: 9 },
        ],
        awayPlayers: [
            { x: 95, y: 50, num: 1, role: 'gk' },
            { x: 55, y: 55, num: 8, hasBall: true },
            { x: 40, y: 65, num: 9 },
            { x: 42, y: 45, num: 11 },
        ],
        arrows: [
            { fromX: 35, fromY: 80, toX: 35, toY: 85, type: 'press' },
            { fromX: 35, fromY: 60, toX: 35, toY: 67, type: 'press' },
            { fromX: 35, fromY: 40, toX: 35, toY: 47, type: 'press' },
            { fromX: 35, fromY: 20, toX: 35, toY: 27, type: 'press' },
        ],
        question: 'Vad ropar mittbacken (4)?',
        options: [
            '¡Línea! ¡Arriba todos!',
            '¡Baja a defender!',
            '¡Cambia el juego!',
            '¡Suelta rápido!',
        ],
        correctIndex: 0,
        explanation: '"¡Línea!" = håll linjen. Alla backar går upp samtidigt för att sätta motståndaren offside.',
    },
    {
        id: 'hombre',
        title: 'Man bakom!',
        situation: 'Mittfältaren (10) tar emot bollen med ryggen mot mål. En motståndare smyger bakom honom.',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 22, y: 75, num: 2 },
            { x: 20, y: 55, num: 4 },
            { x: 20, y: 45, num: 5 },
            { x: 22, y: 25, num: 3 },
            { x: 40, y: 60, num: 6 },
            { x: 38, y: 40, num: 8 },
            { x: 50, y: 20, num: 7 },
            { x: 55, y: 50, num: 10, hasBall: true },
            { x: 50, y: 80, num: 11 },
            { x: 68, y: 50, num: 9 },
        ],
        awayPlayers: [
            { x: 95, y: 50, num: 1, role: 'gk' },
            { x: 75, y: 65, num: 2 },
            { x: 72, y: 50, num: 5 },
            { x: 75, y: 35, num: 4 },
            { x: 58, y: 52, num: 6, highlight: true },
        ],
        arrows: [
            { fromX: 58, fromY: 52, toX: 56, toY: 51, type: 'press' },
        ],
        question: 'Vad varnar lagkamraten (8)?',
        options: [
            '¡Hombre detrás, suelta rápido!',
            '¡Gira que estás solo!',
            '¡Tira a portería!',
            '¡Aguanta el balón!',
        ],
        correctIndex: 0,
        explanation: '"¡Hombre detrás!" = man bakom dig! En varning att passa av snabbt innan motståndaren tar bollen.',
    },
    {
        id: 'cambio',
        title: 'Byt sida',
        situation: 'Spelet är överbelastat på vänsterkanten. Det finns massor av yta på högerkanten där yttern (11) är fri.',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 22, y: 75, num: 2 },
            { x: 20, y: 58, num: 4 },
            { x: 20, y: 42, num: 5 },
            { x: 22, y: 25, num: 3 },
            { x: 38, y: 35, num: 6, hasBall: true },
            { x: 42, y: 50, num: 8 },
            { x: 45, y: 22, num: 7 },
            { x: 48, y: 35, num: 10 },
            { x: 55, y: 82, num: 11, highlight: true },
            { x: 62, y: 45, num: 9 },
        ],
        awayPlayers: [
            { x: 95, y: 50, num: 1, role: 'gk' },
            { x: 75, y: 70, num: 2 },
            { x: 72, y: 50, num: 5 },
            { x: 72, y: 35, num: 4 },
            { x: 55, y: 40, num: 6 },
            { x: 52, y: 28, num: 8 },
        ],
        arrows: [
            { fromX: 38, fromY: 35, toX: 52, toY: 80, type: 'pass', label: '?' },
        ],
        question: 'Vad ropar tränaren?',
        options: [
            '¡Cambia el juego a la otra banda!',
            '¡Cierra el espacio!',
            '¡Replieguen todos!',
            '¡Presiona arriba!',
        ],
        correctIndex: 0,
        explanation: '"Cambiar el juego" = byt sida. En lång passning till den fria kanten bryter motståndarens press.',
    },
    {
        id: 'cobertura',
        title: 'Täckning',
        situation: 'Högerbacken (2) har gått upp i anfall. Mittbacken (4) behöver täcka ytan bakom.',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 55, y: 85, num: 2 },
            { x: 25, y: 65, num: 4, highlight: true },
            { x: 22, y: 45, num: 5 },
            { x: 22, y: 25, num: 3 },
            { x: 40, y: 60, num: 6 },
            { x: 42, y: 45, num: 8 },
            { x: 50, y: 25, num: 7 },
            { x: 58, y: 65, num: 10, hasBall: true },
            { x: 60, y: 28, num: 11 },
            { x: 68, y: 50, num: 9 },
        ],
        awayPlayers: [
            { x: 95, y: 50, num: 1, role: 'gk' },
            { x: 75, y: 70, num: 3 },
            { x: 72, y: 50, num: 5 },
            { x: 60, y: 40, num: 8 },
            { x: 40, y: 78, num: 11 },
        ],
        arrows: [
            { fromX: 25, fromY: 65, toX: 30, toY: 78, type: 'run' },
        ],
        question: 'Vad ropar mittbacken (5) till mittbacken (4)?',
        options: [
            '¡Dame cobertura al lateral!',
            '¡Tira a portería!',
            '¡Al primer toque!',
            '¡Vamos a ganar!',
        ],
        correctIndex: 0,
        explanation: '"Cobertura" = täckning. Mittbacken skiftar över för att täcka ytan som högerbacken lämnat.',
    },
    {
        id: 'solo',
        title: 'Du är fri!',
        situation: 'Anfallaren (9) har fått ett perfekt läge helt fri framför mål efter en djupledsboll.',
        homePlayers: [
            { x: 5, y: 50, num: 1, role: 'gk' },
            { x: 25, y: 75, num: 2 },
            { x: 22, y: 55, num: 4 },
            { x: 22, y: 45, num: 5 },
            { x: 25, y: 25, num: 3 },
            { x: 45, y: 60, num: 6 },
            { x: 48, y: 45, num: 8 },
            { x: 50, y: 25, num: 7 },
            { x: 55, y: 55, num: 10 },
            { x: 55, y: 80, num: 11 },
            { x: 82, y: 52, num: 9, hasBall: true, highlight: true },
        ],
        awayPlayers: [
            { x: 92, y: 50, num: 1, role: 'gk' },
            { x: 75, y: 65, num: 4 },
            { x: 75, y: 40, num: 5 },
        ],
        arrows: [
            { fromX: 82, fromY: 52, toX: 90, toY: 55, type: 'pass', label: '!' },
        ],
        question: 'Vad skriker lagkamraterna?',
        options: [
            '¡Estás solo, tira!',
            '¡Pásala atrás!',
            '¡Hombre detrás!',
            '¡Baja a defender!',
        ],
        correctIndex: 0,
        explanation: '"¡Estás solo, tira!" = du är fri, skjut! Spelaren är i ett perfekt skottläge.',
    },
];
